<html>
<head>
<title>Ejemplo!</title>
<link rel="stylesheet" href="/css/bootstrap.min.css" />
<script src="/js/jquery.js" language="javascript"> </script>
<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" language="javascript"> </script-->
<script src="/js/bootstrap.min.js" language="javascript"> </script>
</head>
<body>
<?php $this->renderPartial() ?>
</body>
</html>