<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Carbono Framework</a>
        </div>
    </div>
</div>
<div class="container">
    <br><br><br><br>
    <h1><?php echo $this->dato ?></h1>
    <pre>
        Version del Framework : <?php echo Carbono_Version::VERSION ?><br />
        Nombre del Framework : <?php echo Carbono_Version::NAME_FRAMEWORK ?>
    </pre>
</div>